### ISSUE TITLE
Tool failed error

### ISSUE THREAD

**Issue by dyermd** [rabix/rabix#137]
Running rabix on a workflow and all I get is a generic error with no additional information

```
Tool failed:
<rabix.docker.docker_app.DockerContainer object at 0x107fd3250>
```

There is nothing in the out.err file. Workflow is at https://s3.amazonaws.com/rabix%2Fusers%2Fdyermd%2Fpipelines%2FTest/Test1453738781126.json

**Comment by dyermd** [comment]
Ran in verbose mode to get a little bit more information.

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 192.168.99.100
INFO:rabix.cli.cli_app:Running: blasr /mnt/0/ecoli.fastq -sam /mnt/0/ecoli_k12_reference.fasta -out  > /mnt/0/ecoli.sam
INFO:rabix.common.models:File blasr_114342 created.
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: 192.168.99.100

Tool failed:
<rabix.docker.docker_app.DockerContainer object at 0x103c93810>
```

**Comment by dyermd** [comment]
Interesting, just noticed that the command line being run

```
blasr /mnt/0/ecoli.fastq -sam /mnt/0/ecoli_k12_reference.fasta -out  > /mnt/0/ecoli.sam
```

is not the same as what I see in the Rabix UI.

![screen shot 2016-01-26 at 11 46 49 am](https://cloud.githubusercontent.com/assets/7524610/12590896/848bae96-c422-11e5-8ad6-8d00b41dcd4c.png)

**Comment by dyermd** [comment]
Fixed the call to be sure, but still get the same error.

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 192.168.99.100
INFO:rabix.cli.cli_app:Running: blasr /mnt/0/ecoli.fastq /mnt/0/ecoli_k12_reference.fasta -sam -out  > /mnt/0/ecoli.sam
INFO:rabix.common.models:File blasr_114924 created.
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: 192.168.99.100

Tool failed:
<rabix.docker.docker_app.DockerContainer object at 0x10a71b950>
```

**Comment by dyermd** [comment]
Figured it out. It was user error on my part. Looks like the version I was using the `-out` flag does not write to stdout, rather expects a file name. Figured it out by running the command straight through docker. Small feature request would be to print the stdout information like this so user can see it and diagnose easier.

**Comment by StarvingMarvin** [comment]
Yeah, idea was that toll will write any error info on stderr so only that is captured. Stdout is potentially the result of computation so it is left to user to describe how to capture it. Though it does make sense to redirect that too to file if tool description doesn't specify stdout redirect.
