### ISSUE TITLE
--outdir or --dir: neither working

### ISSUE THREAD

**Issue by dyermd** [rabix/rabix#140]
Usage commands show `--outdir`, but options say `--dir`. Both don't work, `--outdir` brings up usage information and `--dir` the output is still put in CWD. Looks like the usage and options sections need to be sync'd and updated.

```
Usage:
    rabix [-v...] [-hcpI] [-t <type>] [-d <dir>] [-i <inp>] [{resources}] <tool> [-- {inputs}...]
    rabix [--outdir=<outdir>] [--quiet] <tool> <inp>
    rabix --conformance-test [--basedir=<basedir>] [--no-container] [--quiet] <tool> <job>
    rabix --version

Options:
  -d --dir=<dir>        Working directory for the task. If not provided one will
                        be auto generated in the current dir.
  -h --help             Show this help message. In conjunction with tool,
                        it will print inputs you can provide for the job.

  -I --install          Only install referenced tools. Do not run anything.
  -i --inp-file=<inp>   Inputs
  -c --print-cli        Only print calculated command line. Do not run anything.
  -p --pretty-print     Print human readable result instead of JSON.
  -t --type=<type>      Interpret given tool json as <type>.
  -v --verbose          Verbosity. More Vs more output.
     --version          Print version and exit.
```

**Comment by StarvingMarvin** [comment]
First about different invocations: The first line is preferred one, and second (and more obviously third) is used for compatibility with conformance testing suit. Second line (--outdir) specifically, doesn't allow for additional parameters to be supplied on command line, and instead all inputs must be specified in input json file passed as positional argument. Anyhow, I believe that --dir only has effect on command line tools. Workflow steps are going to generate their own directories regardless of --dir parameter.

Thinking about it, what could make sense, is that steps are created as subdirectory of passed dir, but than the effect would be the same as if rabix command was executed in that dir.

**Comment by dyermd** [comment]
Thanks for the additional information.
