### ISSUE TITLE
Visual inputs are not created when input type is int

### ISSUE THREAD

**Issue by dyermd** [rabix/rabix#144]
If you create an input on a tool that has type `int` there is not input connecter created on the visual drag-and-drop tool. Switch the type to `File` and it now shows so you can make the connections in a workflow.

I have not tested other types.

**Comment by ntijanic** [comment]
We intentionally only draw ports that use files since there can be lots and lots of "configuration" inputs. The new version (currently on rabix/cottontail) has a switch to toggle visibility of an input port.

**Comment by dyermd** [comment]
Good to know. Don't you have to be able to drag the port to the inputs side though to be able to create the input so you can call it in your `rabix` command?

**Comment by dyermd** [comment]
For example, I added an `int` input on one of my tools and when I drop it in the workflow and try to run it I don't see those options listed; only the file options.

```
[-- --reference=<File> --fastq=<File>...]
```

**Comment by ntijanic** [comment]
@dyermd You should be able to do that by checking the "expose" box next to the parameter. It automatically creates a WF input of same type and pipes it to the tool configuration.

**Comment by dyermd** [comment]
Where is that. On the tool inputs configuration I do not see an expose option

![screen shot 2016-03-09 at 8 06 59 am](https://cloud.githubusercontent.com/assets/7524610/13639458/11806cde-e5ce-11e5-84e5-f111dd85b2da.png)

Likewise on the workflow page for tool input I don't see it

![screen shot 2016-03-09 at 8 07 29 am](https://cloud.githubusercontent.com/assets/7524610/13639470/1d64a6b4-e5ce-11e5-9a97-c86ce5cbf839.png)

**Comment by ntijanic** [comment]
When you click the tool, the panel on the right shows all non-file inputs. Those should have the expose/show checkboxes.

**Comment by dyermd** [comment]
Found it. Thanks.
